In [1]:
# Mayank Singla
# 111901030

In [2]:
import numpy as np  # Importing numpy as np

In [3]:
shots = np.array([1, 2, 3, 4, 6])   # Available Shots
totalBalls = 300        # Total Number of Balls to be delivered
totalWickets = 10       # Total Number of Wickets

# Function to get the probability of getting out by Top Batsman given shot he played(a)
# Based on given information in Question
def pOutMin(a):
    if (a == 1):
        return 0.01
    elif (a == 2):
        return 0.02
    elif (a == 3):
        return 0.03
    elif (a == 4):
        return 0.1
    elif (a == 6):
        return 0.3

# Function to get the probability of getting out by Last Batsman given shot he played(a)
# Based on given information in Question
def pOutMax(a):
    if (a == 1):
        return 0.1
    elif (a == 2):
        return 0.2
    elif (a == 3):
        return 0.3
    elif (a == 4):
        return 0.5
    elif (a == 6):
        return 0.7

# Function to get the probability of getting out given number of wickets in hand(w) and shot played(a)
# Based on given information in Question
def pOut(w, a):
    return pOutMax(a) + (((pOutMin(a) - pOutMax(a)) * (w - 1)) / 9)

In [5]:
n = totalBalls + 1      # Number of rows of Matrix
m = totalWickets + 1    # Number of columns of Matrix

# Best Score array that gives best score when number of balls left are b and number of wickets in hand are w
bestScore = np.zeros((n, m))

# Best Score array that gives best shot to play when number of balls left are b and number of wickets in hand are w
bestShot = np.zeros((n, m))

# Computing results based on recurrence relation derived in notes
for b in range(n):      # For each number of balls left b
    if (b == 0): continue   # Continue for number of balls = 0 as result is 0

    for w in range(m):  # For each number of wickets left w
        if (w == 0): continue   # Continue for number of wickets left = 0 as result is 0
        if (totalWickets - w > totalBalls - b): continue    # As it is not possible that number of wickets fallen is greater than number of balls delivered
        maxScore = 0      # Max Score that can be obtained
        maxShot = 0       # Best Shot to play

        for a in shots: # Looping all the available shots
            # Score that can be obtained by playing this current shot
            score = ((1 - pOut(w, a)) * (a + bestScore[b-1][w])) + (pOut(w, a) * bestScore[b-1][w-1])

            if (score > maxScore):  # If current score is greater than maxScore obtained so far
                maxScore = score    # Update max score
                maxShot = a         # Update best shot
            elif ((score == maxScore) and (a > maxShot)):   # If for same score we can get more runs
                maxShot = a     # Update best shot

        bestScore[b][w] = maxScore  # Putting the max score obtained
        bestShot[b][w] = maxShot    # Putting the best shot obtained

print("Best Scores:")
print(bestScore)

print("===================================")

print("Best Shots:")
print(bestShot)

Best Scores:
[[  0.           0.           0.         ...   0.           0.
    0.        ]
 [  0.           2.1          2.19       ...   3.66666667   3.93333333
    4.2       ]
 [  0.           3.57         4.3557     ...   7.22962963   7.77481481
    8.32      ]
 ...
 [  0.           0.           0.         ... 134.81772473 183.24687204
  279.74780612]
 [  0.           0.           0.         ...   0.         183.25828909
  279.77778744]
 [  0.           0.           0.         ...   0.           0.
  279.80739748]]
Best Shots:
[[0. 0. 0. ... 0. 0. 0.]
 [0. 3. 3. ... 6. 6. 6.]
 [0. 3. 3. ... 6. 6. 6.]
 ...
 [0. 0. 0. ... 1. 1. 2.]
 [0. 0. 0. ... 0. 1. 2.]
 [0. 0. 0. ... 0. 0. 2.]]
