In [ ]:
# Mayank Singla
# 111901030

In [1]:
import numpy as np  # Importing numpy as np
import heapq        # Importing heapq for min Priority Queue

In [2]:
dx = [0, -1, 0, 1]  # Delta values in x for going Left, Up, Right, Down
dy = [1, 0, -1, 0]  # Delta values in y for going Left, Up, Right, Down

In [3]:
# Function to check if the given position in grid is valid or not
def isValid(point, n, grid, explored):
    (i, j) = point
    # It should be in range of grid
    # It should not be a blocked position
    # It should not be explored already
    return (i >= 0 and j >= 0 and i < n and j < n and grid[i][j] != -1 and explored[i][j] != 1)

# Function to return the cost between two given points
def getDistance(p1, p2):
    return np.abs(p1[0] - p2[0]) + np.abs(p1[1] - p2[1])

# Function to return f(n) = g(n) + h(n)
def fn(p, start, goal):
    return getDistance(p, start) + getDistance(p, goal);

# Function to print the final path obtained and the cost of path
def printStates(parent, point):
    (x, y) = point
    path = []       # Path list of points
    while (x != -1 and y != -1): # Tracing back path from goal to start
        path.append((x, y))
        (x, y) = parent[x][y]

    print("Path Found:", end = " ")
    for i in range(len(path) - 1, -1, -1):  # Printing path in reverse order as points were added in reverse order
        print(path[i], end = " ")
        if (i != 0):
            print("=>", end = " ")

    print()
    print("Cost: " + str(len(path) - 1))    # Printing the cost of the path

In [8]:
# Q1 and Q2

# Function to perfrom BFS or DFS
# n = size of grid
# countBlocked = number of blocked positions
# blockedPos = array of points of blocked positions
# goalState = goal state
# sign = +1 for BFS
# sign = -1 for DFS
def search(n, countBlocked, blockedPos, start, goal, sign):
    empty = 5           # Function to denote empty position in the grid (None of start, goal, blocked, explored, frontier)
    (sx, sy) = start    # Start position
    
    grid = np.zeros((n, n)) # nXn grid
    grid.fill(empty)        # Filling all the positions initally as empty
    grid[sx][sy] = 0        # Marking start position as 0

    status = np.zeros((n, n))   # nXn status matrix to keep track of status of algorithm
    status.fill(empty)          # Filling all the positions initally as empty
    status[sx][sy] = 0          # Marking start position as 0

    cost = np.zeros((n, n)) # nXn cost matrix to keep track of cost of path from start position

    for (x, y) in blockedPos:   # Marking all the given blocked positions as -1
        grid[x][y] = -1
        status[x][y] = -1
        cost[x][y] = 100000     # cost of going to a blocked position is INF = 100000 here
    
    # Marking goal state as 1 in grid and status
    fx, fy = goal
    grid[fx][fy] = 1
    status[fx][fy] = 1

    explored = np.zeros((n, n)) # To keep track of explored list

    parent = np.empty((n, n), dtype = object)   # To keep track of parent of each position
    parent.fill((-1, -1))

    pq = []         # Priority Queue of (fn, point), priority based on sign * f(n)
    pq.append((sign * fn(start, start, goal), (sx, sy)))   # Pushing initial state
    heapq.heapify(pq)       # Heapifying it to make it a priority queue

    found = 0       # To keep track of whether we obtained goal state or not
    while (len(pq) > 0):    # While there are nodes in the Priority Queue
        (f, (x, y)) = heapq.heappop(pq) # Poping out the lowest priority node

        if (explored[x][y] == 1):   # If it is already explored then continue
            continue

        explored[x][y] = 1  # Marking it as explored
        status[x][y] = 3    # Marking its status as Frontier = 3
        print("=================================")
        print("Current Status:")
        print(status)
        print("=================================")
        status[x][y] = 2    # Marking its status as Explored = 2

        if (grid[x][y] == 1):   # If it is goal state
            print("Goal State Found!!")
            found = 1   # Marking found as 1
            printStates(parent, (x, y)) # Printing path and cost
            break   # Terminating as we have found the goal state

        for i in range(4):  # Exploring all the neighbours of the current cell in four directions
            newX, newY = x + dx[i], y + dy[i]   # Coordinates of neighbour cell

            if (isValid((newX, newY), n, grid, explored)):  # If it is a valid cell
                heapq.heappush(pq, (sign * fn((newX, newY), start, goal), (newX, newY)))  # Pushing the node to the priority queue
                parent[newX][newY] = (x, y)         # Updating parent
                cost[newX][newY] = cost[x][y] + 1   # Updating cost
    
    if (found == 0):    # If we can't find any goal state
        print("No Goal State Found!!")

# Example BFS
# search(5, 2, [(1, 2), (2, 3), (4, 0), (3, 3), (4, 2)], (0, 0), (4, 4), 1)
# print()
# search(5, 8, [(1, 1), (1, 2), (1, 3), (2, 1), (2, 3), (3, 1), (3, 2), (3, 3)], (0, 0), (2, 2), -1)
# print()

# Example DFS
# search(5, 0, [(1, 2), (2, 3)], (0, 0), (2, 4), -1)
# print()
# search(5, 4, [(1, 2), (2, 1), (2, 3), (3, 2)], (0, 0), (2, 2), -1)
# print()

# Viva BFS
search(10, 7, [(3, 3), (3, 4), (3, 5), (4, 3), (4, 5), (5, 3), (5, 5)], (0, 0), (4, 4), 1)

# Viva DFS
# search(10, 7, [(3, 3), (3, 4), (3, 5), (4, 3), (4, 5), (5, 3), (5, 5)], (0, 0), (4, 4), -1)

Current Status:
[[ 3.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5. -1. -1. -1.  5.  5.  5.  5.]
 [ 5.  5.  5. -1.  1. -1.  5.  5.  5.  5.]
 [ 5.  5.  5. -1.  5. -1.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]]
Current Status:
[[ 2.  3.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5. -1. -1. -1.  5.  5.  5.  5.]
 [ 5.  5.  5. -1.  1. -1.  5.  5.  5.  5.]
 [ 5.  5.  5. -1.  5. -1.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]]
Current Status:
[[ 2.  2.  3.  5.  5.  5.  5.  5.  5.  5.]
 [ 5.  5.  5.  5.  5.  5.  5.  5.  5.  5.]
 [ 5

In [ ]:
# Q3

# Function to find the positions of all the empty spaces in the given grid
def getEmptySpaces(grid, goal = []):
    emptySpaces = []    # list of empty points
    for i in range(len(grid)):  # Looping all the rows
        for j in range(len(grid[i])):   # Looping all the points in the row
            if (grid[i][j] == 0):        # if label is 0, it is an empty space
                emptySpaces.append((i, j))  # Adding it to final list
    return np.array(emptySpaces)

# Function to get the Goal State configuration for nXm matrix given number of empty spaces
def getGoalState(n, m, countEmpty):
    goal = np.zeros((n, m), dtype = int)    # nXm matrix
    count = 1
    for i in range(n):  # Filling all the rows
        for j in range(m):  # Filling all the points in the row
            goal[i][j] = count
            count += 1
            if (count > ((n * m) - countEmpty)):    # If we have filled all the possible spaces, break
                break
        
        if (count > ((n * m) - countEmpty)):    # If we have filled all the possible spaces, break
            break
    return goal

# Function to check if the given position of point is valid or not
def isValidPos(i, j, n, m):
    return (i >= 0 and j >= 0 and i < n and j < m)  # It should be in the range of given matrix

# Function to get the nXm array out of the given bytes string of the array
# Getting back nXm array from str = arr.tobytes()
def getArray(n, m, arrStr):
    # bytearray() so that we can get a mutable array finally
    # Reshaping it to nXm shape array
    return np.frombuffer(bytearray(arrStr), dtype = int).reshape((n, m))

# Function to get the heuristic of the grid configuration as mentioned in the question
# count = number of empty spaces
def getHeuristic(n, m, gridStr, count):
    sum = 0 # Final sum of distances
    grid = getArray(n, m, gridStr)  # Getting the grid
    index = (n * m - count) + 1 # Number of least empty space in goal state
    for i in range(n):  # Looping all rows
        for j in range(m):  # Looping all points in rows
            if (grid[i][j] != 0):   # If it is not empty space
                sx, sy = (grid[i][j] - 1) // m, (grid[i][j] - 1) % m    # The x and y coordinates
                sum += getDistance((i, j), (sx, sy))    # Adding distance to sum
            else:
                sx, sy = (index - 1) // m, (index - 1) % m  # The x and y coordinates
                index += 1  # incrementing number of empty space
                sum += getDistance((i, j), (sx, sy))    # Adding distance to sum
    return sum

In [ ]:
# Function to get the action performed given new coordinates of point and old coordinates of points
def getAction(x, y, nx, ny):
    diffX = nx - x  # Getting the difference in x-coordinates
    diffY = ny - y  # Getting the difference in y-coordinates
    # Returning the corresponding string of action performed based on above values
    if (diffX == 0 and diffY == 1):
        return "Right"
    elif (diffX == -1 and diffY == 0):
        return "Up"
    elif (diffX == 0 and diffY == -1):
        return "Left"
    elif (diffX == 1 and diffY == 0):
        return "Down"

# Function to print the path from the start state to the goal state and the number of steps performed
def printPath(parent, steps, goalStr, initGridStr, n, m):
    path = []   # path list of grid
    step = []   # action performed on each step of solution
    gridStr = goalStr   # The bytes string of goal state grid
    while (gridStr != initGridStr): # Tracing route back to the start state from goal state
        grid = getArray(n, m, gridStr)  # Getting back the array
        path.append(grid)   # Appending it to the list
        step.append(steps[gridStr]) # Getting the corresponding action performed
        gridStr = parent[gridStr].tobytes() # Going to parent

    path.reverse()  # Reversing because they were added in reverse order in the list
    step.reverse()  # Reversing because they were added in reverse order in the list

    print("============================")
    print("Initial State:\n", getArray(n, m, initGridStr))  # Printing inital state of Grid

    for i in range(len(path)):  # Printing all the steps performed to find the solution
        x, y, nx, ny = step[i]
        print("============================")
        print("Step " + str(i+1) + ": " + "From (" + str(x) + ", " + str(y) + ") Go " + str(getAction(x, y, nx, ny)) + " To (" + str(nx) + ", " + str(ny) + ")")
        print("New State:")
        print(path[i])
    
    print("============================")
    print("Number of steps:", len(path))    # printing number of steps taken

In [ ]:
# Function to solve the given puzzle
# Storing everything as bytes string rather than whole grid to reduce time and space complexity
# initGrid = initial grid to solve
# Goal = final goal state grid to reach, if not given it will be the default final state of the original puzzle
# label = 0 for an empty space in the grid
def puzzle(initGrid, goal = []):
    initGrid = np.array(initGrid)   # Converting it to numpy array
    n1 = len(initGrid)  # Number of rows of grid
    if (n1 == 0):   # If there are no rows
        return
    m1 = len(initGrid[0])   # Number of columns of the grid
    initGridStr = initGrid.tobytes()    # Initial bytes string of initial grid

    initEmptySpaces = getEmptySpaces(initGrid)  # Getting the empty spaces position in the grid
    n2 = len(initEmptySpaces)   # Number of empty spaces, label = 0
    if (n2 == 0):   # If there are no empty spaces
        return
    m2 = len(initEmptySpaces[0])    # Dimension of points (= 2)

    if (goal == []):    # If goal state is not given
        goal = getGoalState(n1, m1, n2) # Getting the original goal state of the puzzle
    else:
        goal = np.array(goal)   # Converting goal state to numpy array
    goalStr = goal.tobytes()    # Goal bytes string

    index = 0     # Index to keep track of which empty space we are moving
    explored = {initGridStr}   # list of bytes string of explored configurations of grid
    parent = {}     # Parent dictionary of (bytes string, parent grid) to trace back route
    steps = {}      # Steps dictionary of (bytes string, (x, y, nx, ny)) to keep track of what action was performed

    pq = []     # Priority Queue of (f(n), cost, grid_bytes_string, empty_spaces_bytes_string), priority based on f(n)
    pq.append((0 + getHeuristic(n1, m1, initGridStr, len(initEmptySpaces)), 0, initGridStr, initEmptySpaces.tobytes()))    # Adding inital states
    heapq.heapify(pq)   # Heapifying it to make it a priority queue

    parent[initGridStr] = -1        # Parent is Null for initial configuration
    steps[initGridStr] = (-1, -1, -1, -1)   # Null actions

    found = 0   # To keep track of whether we obtain a solution finally or not
    while (len(pq) > 0):    # While there are nodes in the priority queue
        (f, c, gridStr, emptySpacesStr) = heapq.heappop(pq)    # Poping the lowest priority node from the priority queue
        
        grid = getArray(n1, m1, gridStr)    # Getting the grid from the grid bytes string
        emptySpaces = getArray(n2, m2, emptySpacesStr)  # Getting the empty spaces from the empty spaces bytes string
        x, y = emptySpaces[index]   # Current empty space taken into consideration
        
        for i in range(4):  # Exploring all the four directions of current empty space
            newX = x + dx[i]    # x-coordinate of the neighbour
            newY = y + dy[i]    # y-coordinate of the neighbour

              # If it is a valid position and we are not swapping two empty spaces
            if (isValidPos(newX, newY, n1, m1) and grid[newX][newY] != 0):
                val = grid[newX][newY]  # Previous value on the neighbour in the grid
                grid[newX][newY] = 0    # Moving space
                grid[x][y] = val        # Moving value
                newGridStr = grid.tobytes() # Getting the new bytes string of the new configuration of the grid
                grid[newX][newY] = val  # Backtrack to move prev val back to original position
                grid[x][y] = 0  # Backtrack to move space back to original position

                if (not (newGridStr in explored)):  # If this configuration is not previously explored
                    # Updating the new position of the empty spaces
                    emptySpaces[index][0] = newX
                    emptySpaces[index][1] = newY
                    newEmptySpacesStr = emptySpaces.tobytes()   # New empty spaces bytes string obtained
                    # Backtracking to previous positions of empty spaces
                    emptySpaces[index][0] = x
                    emptySpaces[index][1] = y

                    heapq.heappush(pq, (c + 1 + getHeuristic(n1, m1, newGridStr, len(emptySpaces)), c + 1, newGridStr, newEmptySpacesStr))    # Pushing new node to the priority queue
                    explored.add(newGridStr)     # Adding this new configuration of grid to explored list
                    parent[newGridStr] = grid       # Parent of new configuration as grid
                    steps[newGridStr] = (x, y, newX, newY)  # Updating action performed

                    if (gridStr == goalStr):    # If new configuration found is the goal state configuration
                        print("Solution Found!!")
                        found = 1   # We have found the solution
                        printPath(parent, steps, goalStr, initGridStr, n1, m1)  # Printing the final solution
                        break   # Terminating as we have found the solution
        
        if (found == 1):    # If we have found the solution, terminate the execution
            break
        
        index = (index + 1) % len(emptySpaces)  # Incrementing the index so as to loop over empty spaces in cyclic manner

    if (found == 0):    # If found = 0, we can't solve the given initial configuration of the grid
        print("No Solution Exists!!")

puzzle([[2, 6, 0], [4, 3, 7], [5, 0, 1]])   # Solving the given puzzle

Solution Found!!
Initial State:
 [[2 6 0]
 [4 3 7]
 [5 0 1]]
Step 1: From (0, 2) Go Left To (0, 1)
New State:
[[2 0 6]
 [4 3 7]
 [5 0 1]]
Step 2: From (2, 1) Go Right To (2, 2)
New State:
[[2 0 6]
 [4 3 7]
 [5 1 0]]
Step 3: From (0, 1) Go Down To (1, 1)
New State:
[[2 3 6]
 [4 0 7]
 [5 1 0]]
Step 4: From (2, 2) Go Up To (1, 2)
New State:
[[2 3 6]
 [4 0 0]
 [5 1 7]]
Step 5: From (1, 1) Go Down To (2, 1)
New State:
[[2 3 6]
 [4 1 0]
 [5 0 7]]
Step 6: From (2, 1) Go Right To (2, 2)
New State:
[[2 3 6]
 [4 1 0]
 [5 7 0]]
Step 7: From (1, 2) Go Up To (0, 2)
New State:
[[2 3 0]
 [4 1 6]
 [5 7 0]]
Step 8: From (2, 2) Go Left To (2, 1)
New State:
[[2 3 0]
 [4 1 6]
 [5 0 7]]
Step 9: From (0, 2) Go Left To (0, 1)
New State:
[[2 0 3]
 [4 1 6]
 [5 0 7]]
Step 10: From (2, 1) Go Left To (2, 0)
New State:
[[2 0 3]
 [4 1 6]
 [0 5 7]]
Step 11: From (2, 0) Go Up To (1, 0)
New State:
[[2 0 3]
 [0 1 6]
 [4 5 7]]
Step 12: From (1, 0) Go Right To (1, 1)
New State:
[[2 0 3]
 [1 0 6]
 [4 5 7]]
Step 13: From (